# Generated by Django 4.0.2 on 2022-02-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shorturl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longurl', models.CharField(max_length=300)),
                ('shorturl', models.CharField(max_length=300)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
